# Generated by Django 5.1.2 on 2024-10-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FraMqueli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='project/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
